### ISSUE TITLE
Newly generated pipeline fails with `ImportError: cannot import name 'OAuth2ClientCredentials'`

### ISSUE THREAD

**Issue by joscha** [dlt-hub/dlt-init-openapi#130]
A freshly generated pipeline with:

```
dlt-init-openapi affinity --url https://raw.githubusercontent.com/planet-a-ventures/affinity-node/refs/heads/main/openapi/2024-11-18.json --global-limit 2
```
yields
```
Traceback (most recent call last):
  File "/Users/joscha/dev/dlt-test/affinity_pipeline/affinity_pipeline.py", line 3, in <module>
    from affinity import affinity_source
  File "/Users/joscha/dev/dlt-test/affinity_pipeline/affinity/__init__.py", line 5, in <module>
    from rest_api import rest_api_source
  File "/Users/joscha/dev/dlt-test/affinity_pipeline/rest_api/__init__.py", line 39, in <module>
    from .config_setup import (
  File "/Users/joscha/dev/dlt-test/affinity_pipeline/rest_api/config_setup.py", line 47, in <module>
    from dlt.sources.helpers.rest_client.auth import (
ImportError: cannot import name 'OAuth2ClientCredentials' from 'dlt.sources.helpers.rest_client.auth' (/Users/joscha/dev/dlt-test/.devenv/state/venv/lib/python3.11/site-packages/dlt/sources/helpers/rest_client/auth.py)
```
on running the pipeline. Possibly related to an outdated dlt version?

**Comment by joscha** [comment]
Upgrading dlt is not as straightforward as hoped: https://github.com/dlt-hub/dlt-init-openapi/issues/127#issuecomment-2488306248

**Comment by joscha** [comment]
Changing the `requirements.txt` to `dlt>=0.5.2, <1` seems to resolve this issue.

**Comment by gregorywaynepower** [comment]
@joscha Have you tested this with `dlt==1.6.1`?

**Comment by joscha** [comment]
> [@joscha](https://github.com/joscha) Have you tested this with `dlt==1.6.1`?

no, sorry, I moved to a custom implementation

**Comment by gregorywaynepower** [comment]
@joscha Is that across the board with your submitted PR's, or just for this particular issue? I may try tackling this issue of getting this up to speed with 1.6.1.

**Comment by joscha** [comment]
Just for this particular issue. I ended up using the standard rest client with a generated model from the open API specs I have.
